""""Add_plex_home_and_live_tv_to_invites"

Revision ID: 02b985126361
Revises: 2b54c7468a03
Create Date: 2025-07-19 14:07:33.220461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b985126361'
down_revision = '2b54c7468a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_to_plex_home', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_live_tv', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('allow_live_tv')
        batch_op.drop_column('invite_to_plex_home')

    # ### end Alembic commands ###
