"""Add time format preference to user preferences

Revision ID: 042cecbc08c7
Revises: 00e4195c7282
Create Date: 2025-07-20 15:41:58.045116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042cecbc08c7'
down_revision = '00e4195c7282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_format', sa.String(length=2), nullable=False, server_default='12'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('time_format')

    # ### end Alembic commands ###
