""""add_server_id_to_invites"

Revision ID: 2b54c7468a03
Revises: add_unique_server_names
Create Date: 2025-07-18 20:26:39.094886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b54c7468a03'
down_revision = 'add_unique_server_names'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_accounts_username'), ['username'], unique=True)

    with op.batch_alter_table('invite_usages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mum_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invite_usages_mum_user_id_users', 'users', ['mum_user_id'], ['id'])
        batch_op.drop_column('pum_user_id')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invites_server_id_media_servers', 'media_servers', ['server_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_discord_user_id'))
        batch_op.create_unique_constraint('uq_users_discord_user_id', ['discord_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_discord_user_id'), ['discord_user_id'], unique=1)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('server_id')

    with op.batch_alter_table('invite_usages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pum_user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['pum_user_id'], ['id'])
        batch_op.drop_column('mum_user_id')

    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_accounts_username'))

    # ### end Alembic commands ###
