"""empty message

Revision ID: 45d262a35391
Revises: 02b985126361
Create Date: 2025-07-20 11:16:13.575258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d262a35391'
down_revision = '02b985126361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_user_list_view', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('preferred_user_list_view', sa.String(length=10), server_default='cards', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.drop_column('preferred_user_list_view')
        batch_op.drop_column('sync_user_list_view')

    # ### end Alembic commands ###
