"""add_overseerr_user_links_table

Revision ID: 730c1a9ccff6
Revises: 8e02ece2f856
Create Date: 2025-09-17 08:02:42.133036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730c1a9ccff6'
down_revision = '8e02ece2f856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overseerr_user_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plex_user_id', sa.String(length=255), nullable=False),
    sa.Column('plex_username', sa.String(length=255), nullable=False),
    sa.Column('plex_email', sa.String(length=255), nullable=True),
    sa.Column('overseerr_user_id', sa.Integer(), nullable=True),
    sa.Column('overseerr_username', sa.String(length=255), nullable=True),
    sa.Column('overseerr_email', sa.String(length=255), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('is_linked', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['media_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overseerr_user_links')
    # ### end Alembic commands ###
