"""add_overseerr_fields_to_media_servers

Revision ID: 8e02ece2f856
Revises: add_public_url_to_media_servers
Create Date: 2025-09-17 00:34:04.830020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e02ece2f856'
down_revision = 'add_public_url_to_media_servers'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overseerr_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('overseerr_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('overseerr_api_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_servers', schema=None) as batch_op:
        batch_op.drop_column('overseerr_api_key')
        batch_op.drop_column('overseerr_url')
        batch_op.drop_column('overseerr_enabled')
    # ### end Alembic commands ###
