"""Add server status tracking columns

Revision ID: add_server_status_tracking
Revises: add_user_media_access_to_stream_history
Create Date: 2025-01-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_server_status_tracking'
down_revision = 'add_global_id_uuids'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_status_check', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_status_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_version', sa.String(100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_servers', schema=None) as batch_op:
        batch_op.drop_column('last_version')
        batch_op.drop_column('last_status_error')
        batch_op.drop_column('last_status')
        batch_op.drop_column('last_status_check')

    # ### end Alembic commands ###