"""Add media_items table for caching library content

Revision ID: add_media_items_table
Revises: update_media_stream_history_to_use_uuids
Create Date: 2025-01-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_media_items_table'
down_revision = 'add_library_name_to_stream_history'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('sort_title', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('duration', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('thumb_path', sa.String(length=500), nullable=True),
    sa.Column('art_path', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['media_libraries.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['media_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'external_id', name='uq_library_external_id')
    )
    op.create_index('idx_media_items_added_at', 'media_items', ['added_at'], unique=False)
    op.create_index('idx_media_items_external_id', 'media_items', ['external_id'], unique=False)
    op.create_index('idx_media_items_last_synced', 'media_items', ['last_synced'], unique=False)
    op.create_index('idx_media_items_library_type', 'media_items', ['library_id', 'item_type'], unique=False)
    op.create_index('idx_media_items_title', 'media_items', ['title'], unique=False)
    op.create_index('idx_media_items_year', 'media_items', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_media_items_year', table_name='media_items')
    op.drop_index('idx_media_items_title', table_name='media_items')
    op.drop_index('idx_media_items_library_type', table_name='media_items')
    op.drop_index('idx_media_items_last_synced', table_name='media_items')
    op.drop_index('idx_media_items_external_id', table_name='media_items')
    op.drop_index('idx_media_items_added_at', table_name='media_items')
    op.drop_table('media_items')
    # ### end Alembic commands ###