"""Add external_media_item_id to MediaStreamHistory

Revision ID: add_external_media_item_id
Revises: 527b5672e58b
Create Date: 2025-08-31 16:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_external_media_item_id'
down_revision = '527b5672e58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_stream_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_media_item_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_stream_history', schema=None) as batch_op:
        batch_op.drop_column('external_media_item_id')

    # ### end Alembic commands ###