"""Rename server name fields for clarity

Revision ID: rename_server_name_fields
Revises: add_server_status_tracking
Create Date: 2025-01-24 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'rename_server_name_fields'
down_revision = 'add_server_status_tracking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_servers', schema=None) as batch_op:
        # Rename existing 'name' column to 'server_nickname'
        batch_op.alter_column('name', new_column_name='server_nickname')
        # Add new 'server_name' column for actual server name from service
        batch_op.add_column(sa.Column('server_name', sa.String(255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_servers', schema=None) as batch_op:
        # Remove the server_name column
        batch_op.drop_column('server_name')
        # Rename server_nickname back to name
        batch_op.alter_column('server_nickname', new_column_name='name')

    # ### end Alembic commands ###